### ISSUE TITLE
Potential problem in formula for NRI (NDI)

### ISSUE THREAD

**Issue by CGTZA2** [IngerMathilde/legalPsych#3] opened 2022-05-13 08:06 UTC
When using your very useful package for computing some confidence-accuracy calibration statistics, I noted that the answers I obtained for NRI were not the same as some I had computed myself in Excel, as a check.

I traced the source of this difference to the function calibration(), which is a helper function within CA.REL()

In calibration NRI seems correctly implemented, but it relies on the computation of a, the overall accuracy. 
a <- mean(caltable$`Proportion correct`, na.rm = TRUE) 

That would compute the unweighted proportion accuracy over the confidence bins, but what is really needed I think is the weighted proportion accuracy, or the simpler calculation
a <- sum(caltable$Correct, na.rm = TRUE)/sum(caltable$Total, na.rm = TRUE)

When I change this manually I get the answer that corresponds to my manual calculation.

Just to emphasise this point, consider the following confidence accuracy distribution

Conf bin	Nj	Correct_n
10	5	0
20	48	21
30	51	46

Overall accuracy here is 0.644, but average proportion accuracy as computed by calibration() is 0.446
This leads to an NRI of 0.315 vs an NRI of 0.451

So, my guess is the function needs to be changed, but would appreciate your views

**Comment by renanbsaraiva** [comment] 2022-05-13 09:09
Many thanks for your interest in our package!

I will investigate the issue you are referring to. Just to make sure we are on the same page regarding the calculation of NRI, could you please refer to the reference used for your NRI calculations?

legalPsych was based on the procedures described by Brewer & Wells (2006). Here is a description of the calculation for C and NRI from that paper:

![Untitled](https://user-images.githubusercontent.com/8622079/168249010-7a5b0ed9-d7f5-43e0-b660-5b72152f60b8.png)

![Untitled](https://user-images.githubusercontent.com/8622079/168247230-9e7a2e10-4b77-4bff-8a38-fc9171c785a5.png)

Here is how it is implemented in our function:
a <- mean(caltable$`Proportion correct`, na.rm = TRUE)
  a.j <- caltable$`Proportion correct`
  c.j <- (caltable$`Mean confidence`-confMin)/confMax
  n.j <- caltable$Total
  n.c <- length(c.j)
  n <- sum(caltable$Total, na.rm = TRUE)

  # C, O/U, NRI, and ANRI statistics
  C <- (1/n)*(sum(n.j*(c.j-a.j)^2, na.rm = TRUE))
  OU <- (1/n)*(sum(n.j*(c.j-a.j),  na.rm = TRUE))
  NRI <- ((1/n)*(sum(n.j*(a.j-a)^2, na.rm = TRUE)))/(a*(1-a))
  ANRI <- ((n*NRI)-(n.c+1))/(n-n.c+1)
  calstats = c(C=C, OU = OU, NRI =NRI, ANRI=ANRI)

In that sense, the overall accuracy
_a_ <- mean(caltable$Proportion correct, na.rm = TRUE) seems to be the appropriate measure for NRI, as _a.j_ denotes the proportion of correct responses at confidence level j and _a_ denotes overall mean accuracy.

When describing the overall accuracy, Brewer & Wells (2006) don't seem to refer to a weighted proportion accuracy. The "weight" of each confidence bin (i.e., number of observations) is accounted for by n.j. 

Happy to continue this thread and fix any potential issues you may find though. But in my understanding, the NRI calculation seems adequate as is.

**Comment by CGTZA2** [comment] 2022-05-13 12:16
Dear Renan and team,

Thanks for your prompt reply. I have gone back to the article by Yaniv et al., 1991, and I have computed their example in Figure 1, with results reported on p9 of their article.  I find that I reproduce their results with the formula as adjusted and advised earlier. I have also created an R data file that recreates their dataset, and runs it through calibration(). My results for the R analysis concur with my Excel calculations, in that I reproduce what I think is the incorrect NRI with calibration(), and that matches my calculations in Excel. 

I am attaching the Excel file.  The R script I used to recreate the data and run the analysis is shown below.

Note that I cannot reproduce the ANRI calculation from calibration() in my Excel file.  I think this is because the formula for ANRI is not correct in calibration().  The formula as you have it is 

ANRI <- ((n*NRI)-(n.c+1))/(n-n.c+1)

but I think that should be 

ANRI <- (n*NRI-n.c+1)/(n-n.c+1), see the formula from Yaniv et al below (p 9 in case the image does not paste)

![image](https://user-images.githubusercontent.com/8539114/168280265-15decb3d-fd93-4893-88b4-e03467ff4c99.png)

I also went and changed the formulas inside calibration(), and report the results below, too (but not the code)


R script to reproduce what I think is the incorrect NRI and ANRI
============================================
confidence <- c(rep(0.15,40), rep(0.4,20), rep(0.6,20),rep(0.8,10),rep(1,10))
correct <- c(rep(1,8), rep(0,32), rep(1,10), rep(0,10), 
             rep(1,10), rep(0,10), rep(1,6), rep(0,4),
             rep(1,8), rep(0,2))

mydat <- tibble(confidence, correct)
conf_cal_yaniv <- CA.rel(data = mydat, 
                         confidence = "confidence", 
                         correct = "correct", 
                         test = "CAL",
                         confidenceLevels = list(c(0,.15),c(.16,.40),c(.41,.60),
                                                 c(.61,.80),c(.81,1)),
                         jack = TRUE)
CA.print(conf_cal_yaniv)

Levels   Mean confidence Incorrect Correct Total Proportion correct SE         D   
 0-0.15   0.15            32         8      40    0.2                0.06324555 0.25
 0.16-0.4 0.40            10        10      20    0.5                0.11180340 1.00
 0.41-0.6 0.60            10        10      20    0.5                0.11180340 1.00
 0.61-0.8 0.80             4         6      10    0.6                0.15491933 1.50
 0.81-1   1.00             2         8      10    0.8                0.12649111 4.00

 The C Statistics is:  0.013 ; 95 CI is: -0.006 -  0.032
 The OU Statistics is:  0.020 ; 95 CI is: -0.072 -  0.112
 The NRI Statistics is:  0.199 ; 95 CI is:  0.013 -  0.384
 The ANRI Statistics is:  0.144 ; 95 CI is: -0.049 -  0.338


RESULT FROM REVISED calibration()
==========================

$calstats
          C        C.SE      C.95.L      C.95.H          OU       OU.SE     OU.95.L     OU.95.H         NRI 
 0.21122770  0.04659450  0.11990248  0.30255292 -0.41560000  0.04949282 -0.51260592 -0.31859408  0.16256158 
     NRI.SE    NRI.95.L    NRI.95.H        ANRI     ANRI.SE   ANRI.95.L   ANRI.95.H 
 0.07332586  0.01884289  0.30628026  0.12766831  0.07641326 -0.02210169  0.27743831 


Let me know whether this makes sense
Colin
[andi2.xlsx](https://github.com/IngerMathilde/legalPsych/files/8686932/andi2.xlsx)

**Comment by renanbsaraiva** [comment] 2022-05-13 14:46
Dear Colin,

Many thanks for the code to reproduce the data from Yaniv et al (1991) and for the extra info on ANRI, that was all very helpful. I was able to reproduce the results from the Yaniv paper after implementing your suggestions, so you're absolutely right about the issue with NRI/ANRI. Apologies for the error in the packages and many thanks for bringing that to our attention. 

I have committed those changes to the package now so a redownload of the package should show the correct NRI and ANRI values from now on.

All the best,
Renan

**Comment by CGTZA2** [comment] 2022-05-14 09:36
Dear Renan

Thanks so much for your rapid and careful consideration.  Appreciate it.

One thing you may have thought of - rather than providing Jacknife SEs you could provide Bootstrapped CIs and other statistics. Just a thought.

**Comment by renanbsaraiva** [comment] 2022-05-14 12:13
Dear Colin,

Thanks, I appreciate your attentiveness and lettings us know of the issue, glad it is fixed now.

Those surely sound like interesting additions to the package. I'll do some reading of my own but if you know of any specific important papers would you mind sending them my way at renan.saraiva@port.ac.uk?

**Closed as completed by renanbsaraiva** 2022-05-14 12:13 UTC
